config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :introductions, only: [:new, :edit,:create, :update ,:destroy]

  devise_for :users
  resources :users, only: [:index,:show] do
    get '/followed', to: 'users#followed'
    get '/follower', to: 'users#follower'
  end
  root 'users#top'
  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :comments, only: [:index, :show, :create, :destroy]
  end
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :user, optional: true, foreign_key: 'user_id'
  belongs_to :post, optional: true, foreign_key: 'post_id'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to post_path(@post)}
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @post = Post.find(params[:post_id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="comment-form">
<%= form_for([@post, @post.comments.build]) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2>エラーにより保存できません</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, id: :comment_body ,:size =>"65,1" ,:maxlength => "90"%>
  </div>
  <%= f.hidden_field :post_id %>
  <%= f.hidden_field :user_id %>

  <div class="actions">
    <%= f.submit "送信" , class: "btn btn-outline-secondary btn-sm"%>
  </div>
<% end %>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<div class="post-show-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-sm-6">
        <p><%= link_to @post.user.name, user_path(@post.user_id), class: "post-username" %></p>
        <%= image_tag(@post.image_url(:lager)) %>
        <p>
          <%= @post.content %>
        </p>
      </div>

      <div class="col-lg-6 col-sm-6 post-comment-form">
        <h3>コメントを送りましょう！</h3>
        <div class="comments">
        <% @comments.each do |comment| %>
          <div>
            <strong><%= comment.user.name %></strong>
            <br/>
            <p><%= comment.body %></p>
            <% if user_signed_in? && @post.user == current_user %>
              <p><%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: '削除してもよろしいですか？' } %></p>
            <% end %>
          </div>
        <% end %>
      </div>
        <div class="form">
          <%= render 'comments/form', comment: @comment %>
        </div>
      </div>
    </div>
  </div>
  <%= link_to '戻る', posts_path, class:"back-btn" %>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>