config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :introductions, only: [:new, :edit,:create, :update ,:destroy]

  devise_for :users
  resources :users, only: [:index,:show] do
    get '/followed', to: 'users#followed'
    get '/follower', to: 'users#follower'
  end
  root 'users#top'
  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :comments, only: [:index, :show, :create, :destroy]
  end
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :name,  presence: true, length: { maximum: 20 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :posts, dependent: :destroy
  has_many :introductions, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :followed, :follower]

  def index
    @users = User.all
    @search = User.ransack(params[:q])
    @result = @search.result
  end

  def show
    @user = User.find(params[:id])
  end

  def followed
    @user = User.find(params[:user_id])
  end

  def follower
    @user = User.find(params[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div class="follow-form">
  <div id="follow_form_<%= user.id %>">
    <% if current_user == user %>
      <%= link_to '編集' , edit_user_registration_path , class:"btn btn-outline-secondary btn-sm"%>
    <% else %>
      <% unless current_user.following?(user) %>
        <%= form_with(model: current_user.active_relationships.new(followed_id: user.id) ) do |f| %>
        <%= f.hidden_field :followed_id %>
        <%= f.submit "フォローする", class:"btn btn-light btn-sm" %>
      <% end %>
    <% else %>
      <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "フォロー中" , class:"btn btn-primary btn-sm"%>
    <% end %>
  <% end %>
<% end %>
</div>
</div>

app/views/users/followed.html.erb
<div class="followed-page">
  <h2>フォロー中</h2>
  <div class="followed_users">
  <% @user.following.each do |user| %>
    <% user.introductions.each do |introduction| %>
        <%= image_tag(introduction.image_url(:thumbnail))%>
      <% end %>
      <%= link_to user.name, user_path(user.id), class: "username" %><br><br>
    <% end %>
  </div>
</div>

app/views/users/follower.html.erb
<div class="followed-page">
  <h2>フォロワー</h2>

  <% @user.followers.each do |user| %>
    <% user.introductions.each do |introduction| %>
    <div class="followed_users">
      <%= image_tag(introduction.image_url(:thumbnail))%>
    <% end %>
    <%= link_to user.name, user_path(user.id), class: "username" %><br>
  <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="users-index-page">

  <h2>理想のPhotographerとModelを見つけよう</h2>

  <div class="search-wrap">
    <% provide(:title, 'All posts') %>
      <%= search_form_for @search do |f| %>
      <div class="form-group">
        <%= f.label :category_cont,"カテゴリー" %>
        <%= f.select :category_cont,["カメラマン", "モデル"] , class: "form-control" %>
      </div>
      <div class="actions"><%= f.submit "検索", class:"btn btn-info btn-sm"%></div>
    <% end %>

    <%= link_to "写真一覧はこちら", posts_path, class: "link" %>
  </div>

  <% @result.each do |user| %>
    <div class="user">
      <div class="user-image">
        <% user.introductions.each do |u| %>
          <%= image_tag(u.image_url(:standard))%>
        <% end %>
      </div>
      <div class="user-content">
        <div class="user-name">
          <%= link_to user.name, user_path(user.id), class: "username" %>
          <div class="follow_form"><%= render 'follow_form', user: user %></div>
        </div>
      <div class="user-body">
        <% user.introductions.each do |user| %>
          <%= user.age %><br>
          <%= user.area %><br>
          <%= user.body %>
        <% end %>
      </div>
    </div>
    </div>
    <br>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-page">

  <div class="category">
    <% if @user.category == "カメラマン" %>
      <h2>Photographer</h2>
    <% else %>
      <h2>Model</h2>
    <% end %>
  </div>
  <div class="users-header">
    <div class="header-image">
      <% @user.introductions.each do |user| %>
        <%= image_tag(user.image_url(:thumbnail), class: "image")%>
      <% end %>
    </div>

    <div class="header-content">
      <p><%= @user.name %></p>

      <div class="follow_form"><%= render 'follow_form', user: @user %></div>
      <ul>
        <% if current_user == @user %>
          <li><%= link_to 'メッセージ', conversations_path , class: "list"%></li>

        <% else %>
          <li><%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post ,class: "list"%></li>

        <% end %>
        <li><%= link_to 'フォロー中', user_followed_path(@user), class: "list"%></li>
        <li><%= link_to 'フォロワー', user_follower_path(@user) , class: "list"%></li>
      </ul>

      <div class="Self-introduction">
        <% @user.introductions.each do |user| %>
        <ul>
          <li><p>年齢：<%= user.age %></p></li>
          <li><p>活動エリア：<%= user.area %></p></li>
       </ul>
         <dl id="accordion">
           <dt>プロフィールはこちら</dt>
           <dd><%= user.body %></dd>
         </dl>
          <% if @user == current_user %>
            <div class="btn-group" role="group">
              <button id="btnGroupDrop1" type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
              <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <%= link_to 'プロフィール編集', edit_introduction_path(user) , class: "dropdown-item"%>
              </div>
            </div>
          <% end %>
        <% end %>
        <% if @user.introductions.empty? %>
          <% if @user == current_user %>
            <%= link_to 'まずはプロフィールを追加しましょう！', new_introduction_path , class: "dropdown-item"%>
          <% end %>
        <% end %>
      </div>

    </div>

  </div>

  <div class="user-posts">
    <div class="container">
      <div class="row">
        <% @user.posts.each do |post| %>
          <div class="col-lg-4 col-sm-6">
            <%= image_tag(post.image_url(:standard),class: "image")%>
            <div class="btn-group" role="group">
              <button id="btnGroupDrop1" type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
              <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <%= link_to 'コメントを見る', post , class: "dropdown-item"%>
                <% if post.user == current_user %>
                  <%= link_to '編集', edit_post_path(post) , class: "dropdown-item"%>
                  <%= link_to '削除', post, method: :delete, data: { confirm: 'Are you sure?' } , class: "dropdown-item"%>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">Photographers and Models</h1>
      <p>〜 写真好きのカメラマンとモデルをつなぐサービス 〜</p>
      <h2 class="masthead-subheading mb-0"></h2>
      <% if user_signed_in? %>
      <% else %>
      <a href="users/sign_up" class="btn btn-primary btn-xl rounded-pill mt-5">登録</a>
      <a href="users/sign_in" class="btn btn-primary btn-xl rounded-pill mt-5">ログイン</a>
      <% end %>
      <br><br>
      <p class="notice"><%= notice %></p>
    </div>
  </div>
</header>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <%= image_tag('camera-2598604_640.jpg', class:"img-fluid rounded-circle") %>
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">カメラマン</h2>
          <p>あなたの理想のモデルを見つけることができます。<br>撮影してきた写真を公開し、自分の世界を表現しましょう。</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <%= image_tag('summerfield-336672_640.jpg', class:"img-fluid rounded-circle") %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">モデル</h2>
          <p>あなたの理想のカメラマンを見つけることができます。<br>カメラマンの公開している写真を閲覧し、 理想の世界観を<br>持っている人へ撮影依頼をしましょう。</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <%= image_tag('model-956676_640.jpg', class:"img-fluid rounded-circle") %>
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">最高の一枚を</h2>
          <p>カメラマン、モデルとお互いに理想の相手を見つけ、撮影を楽しみましょう。</p>
        </div>
      </div>
    </div>
  </div>
</section>