config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :introductions, only: [:new, :edit,:create, :update ,:destroy]

  devise_for :users
  resources :users, only: [:index,:show] do
    get '/followed', to: 'users#followed'
    get '/follower', to: 'users#follower'
  end
  root 'users#top'
  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :comments, only: [:index, :show, :create, :destroy]
  end
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/introduction.rb
class Introduction < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true, foreign_key: 'user_id'

  validates :image, presence: true
  validates :area, presence: true
  validates :body, presence: true
end

app/controllers/introductions_controller.rb
class IntroductionsController < ApplicationController
  before_action :set_introduction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /introductions
  # GET /introductions.json
  def index
    @introductions = Introduction.all
  end

  # GET /introductions/1
  # GET /introductions/1.json
  def show
  end

  # GET /introductions/new
  def new
    @introduction = Introduction.new
  end

  # GET /introductions/1/edit
  def edit
    @introduction.user_id = current_user.id
  end

  # POST /introductions
  # POST /introductions.json
  def create
    @introduction = Introduction.new(introduction_params)
    @introduction.user_id = current_user.id
    respond_to do |format|
      if @introduction.save
        format.html { redirect_to user_path(current_user), notice: 'Introduction was successfully created.' }
        format.json { render :show, status: :created, location: @introduction }
      else
        format.html { render :new }
        format.json { render json: @introduction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /introductions/1
  # PATCH/PUT /introductions/1.json
  def update
    respond_to do |format|
      if @introduction.update(introduction_params)
        format.html { redirect_to user_path(current_user), notice: 'Introduction was successfully updated.' }
        format.json { render :show, status: :ok, location: @introduction }
      else
        format.html { render :edit }
        format.json { render json: @introduction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /introductions/1
  # DELETE /introductions/1.json
  def destroy
    @introduction.destroy
    respond_to do |format|
      format.html { redirect_to introductions_url, notice: 'Introduction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_introduction
      @introduction = Introduction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def introduction_params
      params.require(:introduction).permit(:body, :user_id, :age, :area, :image)
    end
end

app/helpers/introductions_helper.rb
module IntroductionsHelper
end

app/views/introductions/_form.html.erb
<div class="post-form">
<%= form_with(model: introduction, local: true) do |form| %>
  <% if introduction.errors.any? %>
    <div id="error_explanation">
      <h2>エラーにより保存できません</h2>

      <ul>
      <% introduction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :年齢 %><br>
    <%= form.text_field :age, :maxlength => "6"%>
  </div>

  <div class="field">
    <%= form.label :活動エリア %><br>
    <%= form.text_field :area, :maxlength => "30"%>
  </div>

  <div class="field">
    <%= form.label :プロフィール %><br>
    <%= form.text_area :body, id: :introduction_body ,:size => "40x3" , :maxlength => "370"%>
  </div>

  <div class="field">
    <%= form.label :プロフィール写真 %><br>
    <%= form.file_field :image, id: :introduction_image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit :value=>"公開する" ,:class=>"btn btn-outline-primary" %>
    <%= link_to '戻る', user_path(current_user) ,class:"btn btn-outline-secondary"%>
  </div>

<% end %>
</div>

app/views/introductions/edit.html.erb
<div class="edit-post">
<h2>編集ページ</h2>

<%= render 'form', introduction: @introduction %>

</div>

app/views/introductions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Introductions</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @introductions.each do |introduction| %>
      <tr>
        <td><%= introduction.body %></td>
        <td><%= introduction.user_id %></td>
        <td><%= link_to 'Show', introduction %></td>
        <td><%= link_to 'Edit', edit_introduction_path(introduction) %></td>
        <td><%= link_to 'Destroy', introduction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Introduction', new_introduction_path %>

app/views/introductions/new.html.erb
<div class="new-post">

<%= render 'form', introduction: @introduction %>
</div>

app/views/introductions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @introduction.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @introduction.user_id %>
</p>

<%= link_to 'Edit', edit_introduction_path(@introduction) %> |
<%= link_to 'Back', introductions_path %>