config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :introductions, only: [:new, :edit,:create, :update ,:destroy]

  devise_for :users
  resources :users, only: [:index,:show] do
    get '/followed', to: 'users#followed'
    get '/follower', to: 'users#follower'
  end
  root 'users#top'
  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :comments, only: [:index, :show, :create, :destroy]
  end
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates :content, presence: true

  belongs_to :user, optional: true, foreign_key: 'user_id'
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.all
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:category, :content, :image, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="post-form">
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2>エラーにより保存できません</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :写真 %>
    <%= form.file_field :image, id: :post_image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :内容 %>
    <%= form.text_area :content, id: :post_content ,:size => "40x3" , :maxlength => "300"%>
  </div>

  <div class="actions">
    <%= form.submit :value=>"公開する" ,:class=>"btn btn-outline-primary" %>
    <%= link_to '戻る', user_path(current_user) ,class:"btn btn-outline-secondary"%>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class="edit-post">
<h2>編集ページ</h2>

<%= render 'form', post: @post %>

<%= link_to '戻る', user_path(current_user) ,class:"btn btn-outline-secondary"%>
</div>

app/views/posts/index.html.erb
<div class="posts-index-page">

  <h2>photogallery</h2>
  <div class="container">
    <div class="row">
      <% @posts.each do |post| %>
        <div class="card">
            <%= link_to post.user.name, user_path(post.user_id), class: "post-username" %>
            <div class="card-img-top">
              <%= image_tag(post.image_url(:standard),class:"image") %></div>
            <div class="body">
              <%= link_to '詳細を見る', post , class: "post-comment"%>
              <% if post.user == current_user %>
                <div class="btn-group" role="group">
                  <button id="btnGroupDrop1" type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                  <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                    <%= link_to '編集', edit_post_path(post) , class: "dropdown-item"%>
                    <%= link_to '削除', post, method: :delete, data: { confirm: 'Are you sure?' } , class: "dropdown-item"%>
                  </div>
                </div>
              <% end %>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="new-post">
<h2>写真を公開しよう！</h2>

<%= render 'form', post: @post %>

</div>

app/views/posts/show.html.erb
<div class="post-show-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-sm-6">
        <p class="name"><%= link_to @post.user.name, user_path(@post.user_id), class: "post-username" %></p>
        <%= image_tag(@post.image_url(:lager)) %>
        <div class="body">
        <p><%= @post.content %></p>
      </div>
      </div>

      <div class="col-lg-6 col-sm-6 post-comment-form">
        <h3>コメントを送りましょう！</h3>
        <div class="comments">
          <% @comments.each do |comment| %>
            <div>
              <strong><%= comment.user.name %></strong>
              <br/>
              <p><%= comment.body %></p>
              <% if user_signed_in? && @post.user == current_user %>
                <p><%= link_to 'Delete', post_comment_path(@post,comment), method: :delete, data: { confirm: '削除してもよろしいですか？' } %></p>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="form">
          <%= render 'comments/form', comment: @comment %>
        </div>
      </div>
    </div>
  </div>
  <%= link_to '戻る', posts_path, class:"back-btn" %>
</div>